# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iC-l-orI0DHJPvHRCGOkuzqvoxS2LO5N
"""

#strings in python

name= "indiradevi"
print(name)

"""**slicling** a **string**"""

string1="letsupgrade"
string2="python class"
print("\nprint slicing of 2nd and 9th characteres")
print(string1[2:9])

"""# **updating **a ***string***"""

string="indusatyam"
print("updating a string")
string="indira devi satyannarayana"
print("updated string is")
print(string)

"""#lenght of a sring"""

string="letsupgrade"

print(len(string))

"""upper case"""

a = "Hello, World!"
print(a.lower())

"""# **lists**



---



"""

a=["indu",2,5,6,8.9,"akka"]
print(type(a))
#length of a list
b= ["apple", "banana", "cherry"]
print(len(b))
#creating a list
c= list(("apple", "banana", "cherry")) # note the double round-brackets
print(c)
#rage of indexing
list2= ["apple", "indu", "cherry", "orange", "mouni", "teja", "mango"]
print(list2[:4])
#changing the value
newone= ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(newone)

"""***DICTIONARIES***

"""

#CREATING DITS
A= {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(A)
#LENGTH
print(len(A))
#TYPE
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))
#ACCESING ELEMENTS
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]
print(x)
#getkeys
k= thisdict.keys()
print(k)